### ISSUE TITLE
add support for vpn gateway resources for vwan module

### ISSUE THREAD

**Issue by dkooll** [CloudNationHQ/terraform-azure-vwan#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

the below resources needs to be supported

azurerm_vpn_gateway
azurerm_vpn_site
azurerm_vpn_gateway_connection

**Comment by emadellaloggia** [comment]
maybe this will help
https://bit.ly/4evXrQ6

you may need to install the c compiler
